version: "3.8"

services:
  frontend:
    restart: always
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_HOST=mysql
      - VITE_USER=${VITE_USER}
      - VITE_PASSWORD=${VITE_PASSWORD}
      - VITE_DATABASE=${VITE_DATABASE}
    depends_on:
      mysql:
        condition: service_healthy # Wait for MySQL to be healthy before starting
    restart: always

  mysql:
    image: mysql:8.0
    container_name: ${VITE_HOST}
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${VITE_PASSWORD}
      - MYSQL_DATABASE=${VITE_DATABASE}
      - MYSQL_USER=${VITE_USER}
      - MYSQL_PASSWORD=${VITE_PASSWORD}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
